bot_name: DexBot
bot_token: telegram_bot_token
duration: 3h

currency: "руб."

db_user: postgres
db_pass: password
db_host: 127.0.0.1
db_port: 5432
db_name: database
db_ssl: disable

css_elements: ".product_price .product_sale_price"

allowed_links: "https://example.org/products/ https://example.org/sales/"
